spring:
  application:
    name: estoque

  datasource:
    url: jdbc:mysql://localhost:3306/estoque
    username: root
    password: Josi1012@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true